### ISSUE TITLE
Will you add the possibility to redefine the totalPages after ajax load?

### ISSUE THREAD

**Issue by rizkytahara** [josecebe/twbs-pagination#1]
Hello,

can you add the possibility to redefine the totalPages?

here is my code:

```
$("ul.pagination", self.$elem).twbsPagination({
    totalPages: 5
    onPageClick: function( event, page ) {
       // call the ajax (i am using another method to do that)
        self.fetch( url, {
            params: $.extend({}, {
                page: page,
            }, options.params)
        }).done(function( result ) {

            // I need to redefine the totalPages after the ajax is done
           // maybe something like:

            $("ul.pagination", self.$elem).twbsPagination({
                totalPages: result.meta.last_page
            });

        });
    }
});
```

**Comment by c3vo** [comment]
I know that init was removed, but this should still work, correct?

Even with init being removed, you're just calling twbsPagination once again and rebuilding the elements once again. This isn't working for me, though.

```
$('#pagination').twbsPagination('destroy');
$('#pagination').twbsPagination({
	visiblePages: 5,
	startPage: 1,
	totalPages: 5,
	onPageClick: function (event, page) {
		getUsers(page);
	}
});
```

Sorry for opening a closed thread, but this is the only thing I could find that was semi-related to my problem.

**Comment by Rahul-Sagore** [comment]
Hi, I am facing the same problem, on ajax call I want to update the total pages in pagination bar. With your solution when I destroy the pagination and re-initialize it, then it throws this error - "Uncaught Error: Start page option is incorrect" + there is no data in $('.pagination').data('currentTotalPages'). Any solutions?

**Comment by Rahul-Sagore** [comment]
Error has been resolved. :) Its working fine.

**Comment by pieroGit** [comment]
Hi, i have same problem and i can't resolve it. i post my code below:

<code>$('#pagination').twbsPagination({
                                totalPages: pagineTotali,
                                visiblePages: 5,
                                onPageClick: function (event, page) {
                                    getInformation(page);
                                }
                            });</code>

i need reload total pages

**Comment by Rahul-Sagore** [comment]
Try to put this code above your pagination code: 
``` $('#pagination').twbsPagination('destroy'); ```
It worked in my case. I was repopulating the pages on ajax, so I need to check if the pagination exist or not then I destroyed it. It worked like a charm.

You can check the pagination data by checking this condition:
``` 
var pageData = $('#pagination').data();
if ( ! pageData.twbsPagination.options.totalPages == total){
    $('#pagination').twbsPagination('destroy'); 
} 
 ```
Note: Need to check this condition or it will throw error on page load since we are trying to destroying it before initialization happens.

Hope this helps!

**Comment by pieroGit** [comment]
hi, thanks! It worked

**Comment by rppig** [comment]
It doesn't work for me with this following code
```
var pageData = $('#pagination').data();
if ( ! pageData.twbsPagination.options.totalPages == total){
    $('#pagination').twbsPagination('destroy'); 
} 
```

 I use this one and it works.
```
if ( $("#pagination").html() !== ''){
            $('#pagination').twbsPagination('destroy');
        }
```

**Comment by Souravb89** [comment]
I might be do a same mistake. Its still throw me an error like twbspagination is not a function. Please help. I am new in jquery


var $pagination = $('#pagination');
	get(baseURL+'/rest/roster/validation-errors', function(data, textStatus, request){
				 
				  records = data.response;
                  //console.log(records);
                  totalRecords = data.response.length;
                  totalPages = Math.ceil(totalRecords / recPerPage);
                  //apply_pagination();
				  //generate_table();
	$pagination.twbsPagination('destroy');// throwing this error here twbspagination is not a function
		$pagination.twbsPagination(init,{
            totalPages: totalPages,
            visiblePages: 6,
            onPageClick: function (event, page) {
                  displayRecordsIndex = Math.max(page - 1, 0) * recPerPage;
                  endRec = (displayRecordsIndex) + recPerPage;
                 
                  displayRecords = records.slice(displayRecordsIndex, endRec);
                  generate_table();
            }
      });
    	

	
});

**Comment by xavierluz** [comment]
https://www.js-tutorials.com/jquery-tutorials/simple-example-pagination-using-jquery-bootstrap/
