### ISSUE TITLE
beforePageClick event needed

### ISSUE THREAD

**Issue by mohandere** [josecebe/twbs-pagination#148]
Hi @esimakin 

Thanks for such great plugin.

For now i am stuck with beforePageClick action. i want to perform some checks/operations before making new page selection.

Could you please help?

**Comment by esimakin** [comment]
Hi!
This feature is not implemented yet.
You can use Promise API and `show` method as workaround.

**Comment by josecebe** [comment]
@mohandere, I added the 'beforePageClick' method.

Check it out please!
