### ISSUE TITLE
hideOnlyOnePage doesn't work

### ISSUE THREAD

**Issue by johnny94** [josecebe/twbs-pagination#159]
I set the totalPages to 1, and then the pagination button doesn't show. The hideOnlyOnePage has been set to `false`, but it seems not work. Do I miss something?

Here is my code
```javascript
var defaultPaginationOpts = {
  totalPages: 1,
  visiblePages: 1,
  initiateStartPageClick: false
};

$pagination = $('#pagination').twbsPagination(defaultPaginationOpts),
```

**Comment by adrienpetel** [comment]
I'm currently facing the same issue. The above code doesn't work with version **1.4.0**, **1.4.1** and **1.3.0**, but work fine with version **1.3.1**

**Comment by johnny94** [comment]
@adrienpetel Thanks, I will try to use version 1.3.1
