### ISSUE TITLE
hideOnlyOnePage and initiateStartPageClick combined

### ISSUE THREAD

**Issue by gekallergis** [josecebe/twbs-pagination#167]
Hello! I am trying to use the paging plugin with initiateStartPageClick set to false in order not to send an initial request out for the first page since I have the data already. Nonetheless, the event is being fired due to the fact that I have the hideOnlyOnePage option set to true to hide paging when there is only one page of data.

I thing the problem is in the following lines (jquery.twbsPagination.js 40-43):

`if (this.options.hideOnlyOnePage && this.options.totalPages == 1) {
            this.$element.trigger('page', 1);
            return this;
        }`

If the option to hide the paging selectors when data is only one page is set to true, then a page change is triggered no matter what the value of hideOnlyOnePage is.

Unless I am missing a specific use case of course :)

**Comment by KrisGerhard** [comment]
I'm facing the same issue.
Similar issue was closed 29 May 2017 https://github.com/esimakin/twbs-pagination/issues/143

**Comment by TarasTD** [comment]
same issue for me :(

**Comment by josecebe** [comment]
Hi @gekallergis , @KrisGerhard and @TarasTD ,

I have fixed this issue, you can test it in 'master' branch. It will be released in 1.4.2 tag (August 1, 2018).

**Comment by gekallergis** [comment]
On my birthdyay :D Thanks a lot for rhe fix

**Comment by Glideh** [comment]
I still have the issue, I guess it's not released yet.
