### ISSUE TITLE
Please release getCurrentPage as patch-update

### ISSUE THREAD

**Issue by svdv22** [josecebe/twbs-pagination#171]
Please release current changes in the master as 1.4.2 (or 1.5.0). Master has the method 'getCurrentPage', you also refer to this page in the documentation. But it's not available in the tag 1.4.1 yet.

**Comment by jbigelow** [comment]
As a workaround you can get the current page via jquery:

$("#my-pager li.page-item.active").text()

**Comment by josecebe** [comment]
This method will be available in 1.4.2 on August 1, 2018. From now, I will try to make a new tag every month if 'master' has changes.
