### ISSUE TITLE
If TotalPages is lesser than VisiblePages, VisiblePages shouldn't be lowered

### ISSUE THREAD

**Issue by josecebe** [josecebe/twbs-pagination#174]
If you create a pagination with 1 page and 10 visible pages, its visible pages variable will change to 1. This will create a conflict with #173 , due to it can change the total pages variable, and pagination will show only 1 visible page.

**Comment by josecebe** [comment]
@esimakin or @AngeIII could someone review it?

This plugin is amazing and needs to have a more active community, I can help you with the issues and pull requests (being a branch manager), even take the control with this plugin if you are not interested in continue with it.

**Comment by esimakin** [comment]
See #176
