### ISSUE TITLE
Looking for a new maintainer...

### ISSUE THREAD

**Issue by esimakin** [josecebe/twbs-pagination#176]
Hello everyone!
I found recenlty that I don't have enough time to manage this repository.
It is nice to see that the plugin is useful for you.

Only principle, that I have followed when I was working on it, is simplicity.
Do not forget it.

Now, I'm looking for a new maintainer.
Please, let me know if you want to maintain it and then provide a short description of yourself.

**Comment by JNPSoftware** [comment]
Hi @esimakin, if someone more experienced is not interested, I have it ok.

**Comment by josecebe** [comment]
Hi,
I am currently using this repo in 2 projects and I found it very useful.

As you said, one of the bests of this plugin is its simplicity, if I am chosen as a new maintainer, I'll keep this principle.

Also I have to say that I'm an open source lover, and I believe in the team work. So, I will be open to discuss with everyone wants to contribute something to the repo.

**Comment by josecebe** [comment]
Any news in here?

**Comment by josecebe** [comment]
I've just renamed my repo

Thanks @esimakin !

**Comment by esimakin** [comment]
Hi!
I'm getting an error when I'm trying to transfer the repo.
You should remove your repo (it still has the same name). Don't forget to save your work in a local repo.

**Comment by josecebe** [comment]
Ok, now I have removed the entire repo and saved my changes locally.

**Comment by esimakin** [comment]
Request is sent
