### ISSUE TITLE
ES6 module

### ISSUE THREAD

**Issue by Glideh** [josecebe/twbs-pagination#178]
This wonderful little plugin seems not to be an importable module.
Well, it seems to rely on jQuery being available globally as $.
Am I wrong ?

If not I would be happy to do a PR about it (not having the time right now tough)

**Comment by josecebe** [comment]
So, the solution is to use 'jQuery' instead of '$'?

In my local machine seems to be working fine replacing all '$' by 'jQuery'.

**Comment by Glideh** [comment]
I personaly aliased `jquery` when I exposed it globally in my webpack config:
```javascript
    plugins: [
        new webpack.ProvidePlugin({
            $: 'jquery'
        }),
    ],
```
