### ISSUE TITLE
Ellipsis in the middle (see http://flaviusmatis.github.io/simplePagination.js/)

### ISSUE THREAD

**Issue by eugenesimakin** [josecebe/twbs-pagination#184]
"Prev 1 2 3 4 5 6 7 ... 6 9 7 Nex" as on page http://flaviusmatis.github.io/simplePagination.js/
ellipsePageSet and labelMap. In short, you can select or enter a page number in the three-dot field.

Thanks for the help.

_Originally posted by @Trzinka in https://github.com/josecebe/twbs-pagination/issues/158#issuecomment-437680493_

**Comment by Trzinka** [comment]
Hi. 

On my side you can see pagination, lazyload and many other things. 

http://www.trzinka.si/Trzinka/index.html 

Robert. 


Od: "Eugene" <notifications@github.com> 
Za: "josecebe/twbs-pagination" <twbs-pagination@noreply.github.com> 
Cc: "Robert Perič" <trzinka@siol.net>, "Mention" <mention@noreply.github.com> 
Poslano: Sreda, 14. November 2018 17:25:53 
Zadeva: [josecebe/twbs-pagination] Ellipsis in the middle (see http://flaviusmatis.github.io/simplePagination.js/) (#184) 



"Prev 1 2 3 4 5 6 7 ... 6 9 7 Nex" as on page http://flaviusmatis.github.io/simplePagination.js/ 
ellipsePageSet and labelMap. In short, you can select or enter a page number in the three-dot field. 

Thanks for the help. 

Originally posted by @Trzinka in #158 (comment)
