### ISSUE TITLE
$('#pagination').twbspagination is not a function 

### ISSUE THREAD

**Issue by GashishGautam** [josecebe/twbs-pagination#188]
I have added the jquery.twbsPagination.js and jquery.twbsPagination.min.js  and separated out the html and js file code and trying to run this with my application and getting this $(...).twbspagination is not a function .Can anyone tell me what is this issue .I have done exactly same https://codepen.io/simoncodrington/pen/bgPYqr  .This example is working fine if I am running only this but integrating with my app then it is not working.

**Comment by eugenesimakin** [comment]
Hi,
If it is not a function then, probably, it is undefined.
Have you tried to check how the script is loading?
