### ISSUE TITLE
Uncaught Error: Start page option is incorrect

### ISSUE THREAD

**Issue by CouldBeFree** [josecebe/twbs-pagination#190]
```
function paginationInit(pages) {
  paginationItem.twbsPagination('destroy');
  paginationItem.twbsPagination({
    totalPages: pages,
    visiblePages: 5,
    next: 'Next',
    prev: 'Prev',
    startPage: current,
    hideOnlyOnePage: true,
    initiateStartPageClick: false,
    onPageClick: function (event, page) {
      var target = $('#label-search');
      appendPagination = false;
      index = page - 1;
      current = page;
    }
  })
}
```
I have this error when  i go the last page of the pagination. I tried this https://github.com/josecebe/twbs-pagination/issues/43#issuecomment-136288053 but with no success. Any ideas?

**Comment by eugenesimakin** [comment]
The answer why the startPage is incorrect is here - [jquery.twbsPagination.js#L21](https://github.com/josecebe/twbs-pagination/blob/master/jquery.twbsPagination.js#L21). Please, check the initial value of the start page.

**Comment by ajeetpal12** [comment]
put (<any> paginationItem).twbsPagination({
