### ISSUE TITLE
Release 1.4.2 is missing?

### ISSUE THREAD

**Issue by robsch** [josecebe/twbs-pagination#198]
Although there is a tag and a branch 1.4.2, there is no Release. That makes troubles with asset-packagist.org, that I included as a repository in my composer.json. It seems that is has been available once, since I already have that version installed, but now this version is not accessible. I don't know if this is a problem with asset-packagist.org or with the missing release or both.

```
$ composer update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires bower-asset/twbs-pagination 1.4.2, found bower-asset/twbs-pagination[v1.4.2] in lock file but not in remote repositories, make sure you avoid updating this package to keep the one from lock file.
```

Could you make it available again?

**Comment by robsch** [comment]
Any news regarding this?

**Comment by josecebe** [comment]
Hi @robsch , I'm taking a look to update the repo. I'll let you now when it's available.

**Comment by robsch** [comment]
Thank you! 

Can it be that you have to update anything for bower as well? I don't know much about it. But when I try to require your package via asset-packagist.org I don't see any versions: https://asset-packagist.org/package/bower-asset/twbs-pagination . I don't know if you know about this site. It is intended to use PHP's composer for bower and npm packages. But it might be a problem of this site. Maybe that it has something to do with the renaming of the repo - and the missing release. If you want to verify this: there is the button 'Fetch updates from Bower' which you could click, so that asset-packagist gets updated with new information.

The alternative regarding asset-packagist.org is using npm. And this works. You can see available versions here: https://asset-packagist.org/package/npm-asset/twbs-pagination .

**Comment by josecebe** [comment]
Hi again @robsch ,

I was able to update npm packages. Try to update your project to 1.4.2 version. For bower I wasn't able to update it, also I think bower is kind of deprecated, so I will keep only the NPM one.

**Comment by robsch** [comment]
Thank you, I'm able to install the package now via https://asset-packagist.org/package/npm-asset/twbs-pagination . 

But is there something wrong with the release 1.4.2? Because it is not declared as "latest release" on [github](https://github.com/josecebe/twbs-pagination/releases).

**Comment by josecebe** [comment]
It was the first release I ever made here on GitHub, so I didn't know the proper steps to make it, and that was the main reason why I didn't released it initially to npm and also it is the reason why I didn't release it properly to GitHub (that's why it doesn't show "latest release" tag). Probably I should have done it this way: https://docs.github.com/es/github/administering-a-repository/managing-releases-in-a-repository

Now I have learned the lesson for next releases 😎, thanks @robsch .

**Comment by robsch** [comment]
Haha ... You're welcome. Learned from me, though I don't know nealry anything regarding github... 
Thank you for you efforts and your package!
