### ISSUE TITLE
disable click event after clicked to link

### ISSUE THREAD

**Issue by pavelthq** [josecebe/twbs-pagination#21]
to prevent nested manipulations with link ( like opening in open tab )
it will be great if you added in function setupEvents

``` javascript
$this.click(function (e) {
                    e.preventDefault();
```

preventDefault solves some problem for me.. and I think it is good to avoid href="javascript:void();"

or you can make it optionally something like

``` javascript
$this.click(function (e) {
                    base.options.preventEvent && e.preventDefault();
```

and make base.options.preventEvent = true

**Comment by vatnoise** [comment]
А оно точно работает? Я когда кликаю на кнопки, меня бросает наверх страницы. Версия v1.3.1

**Comment by AngeIII** [comment]
как бы должен, можете сделать codepen/jsfiddle?
