### ISSUE TITLE
Problem with onPageClick?

### ISSUE THREAD

**Issue by b2z** [josecebe/twbs-pagination#8]
Hi.

I am trying to use your pagination and have a question. I am not a JS-expert, so forgive me if I will write something stupid :)

Here is the code I am using:

``` js
$.ajax({
    type: 'POST',
    url: "/listing-ajax",
    data: {
        'data': data,
    },
    success: function (r) {
        if (r.pagesTotal > 1) {
            $("#pagination").twbsPagination({
                totalPages: r.pagesTotal,
                visiblePages: 5,
                onPageClick: function (event, page) {
                    $.ajax({
                        type: 'POST',
                        url: '/listing-ajax?page=' + page,
                        data: {
                            'data': data,
                        },
                        success: function (data) {
                            // do some stuff
                        }
                    });
                }
            });
        } else {
            $("#pagination").html('');
        }
    }
});
```

As you can see I request some data with AJAX and then init the pagination if total pages more then one. In `onPageClick` I am requesting some new data with the `page` parameter. 

But when the page is loading for the first time I have two AJAX requests:
1. Initial data request.
2. Data request with the page parameter.

Why? Second request should be made only when user clicks on the page link, but seems that it fires during pagination init.

Hope you did understand me :) 
Thanks!

**Comment by C2CCC** [comment]
It seems that the bug still exists in v1.4 when I'm using it.

`<script src="../resources/js/jquery-2.2.4.min.js"></script>
<script src="../resources/bootstrap/js/bootstrap.min.js"></script>
<script src="../resources/js/jquery.twbsPagination1.4.min.js"></script>
<script>
    $(document).ready(function () {
        var obj = {};
        $.ajax({
            url: userAll.url,
            type: userAll.type,
            async: true,
            dataType: 'json',
            data: obj
        }).done(function (data) {
            console.log('get totalPages');
            //page
            var totalPages = data.data.page.totalPages;
            var visiblePages = totalPages < 10 ? totalPages : 10;
            $('#twbsPagination').twbsPagination({
                totalPages: totalPages,
                visiblePages: visiblePages,
                onPageClick: function (event, page) {
                    obj['pageNumber'] = page;
                    $.ajax({
                        url: userAll.url,
                        type: userAll.type,
                        async: true,
                        data: obj,
                        dataType: 'json'
                    }).done(function () {
                        console.log('pageClick fired');
                    });
                }
            });
        });
    });
</script>`

**Comment by emrealyuan** [comment]
I have the same problem. When I loaded the page with document. ready and the onpageclick function will run automatically which means the data was loaded twice. 1st is I sent to page, 2nd is when pagination is loaded the ajax called again. Please see my code and let me know if I did any thing wrong. Thanks a lot.
        $(document).ready(function() {
          //init pagination when page is load
            $('.pagination-demo').twbsPagination({
                    totalPages:  //init from the first load
                    visiblePages: 5, 
                    itemsPerPage: 12,
                    onPageClick: function (event, page) {
                        $.ajax({
                            type:'post',
                            url: //ajax request when click on page,
                            data:{"page":page},
                            success:function(data){
                             // show data on page
                            }
                        });
                    }
            });

        });

**Comment by emrealyuan** [comment]
Found the solution from other post.
initiateStartPageClick: false
Thanks a lot.

**Comment by C2CCC** [comment]
Thank you, emrealyuan and esimakin.

**Comment by akaadir** [comment]
Hi,

when i destroy and initialize new params like totalpages, onPageClick call back event never fires. Below is my code.

       function ShowPages(update, TotalPages) {

            if (update) {

                var $pagination = $('#pagination');
                var defaultOpts = {
                    totalPages: 10
                };
                var totalPages = TotalPages;
                var currentPage = $pagination.twbsPagination('getCurrentPage');
                $pagination.twbsPagination('destroy');
                $pagination.twbsPagination($.extend({}, defaultOpts, {
                    startPage: currentPage,
                    totalPages: TotalPages,
                    first: '<span> <i class="ace-icon fa fa-angle-double-left bigger-140"></i> </span>',
                    prev: '<span> <i class="ace-icon fa fa-angle-left bigger-150"></i></i></span>',
                    next: '<span>  <i class="ace-icon fa fa-angle-right bigger-150"></i></i></span>',
                    last: '<span> <i class="ace-icon fa fa-angle-double-right bigger-140"></i></span>'
                }));
            }
            else {
                $('#pagination').twbsPagination({
                    totalPages: TotalPages,
                    visiblePages: 7,
                    first: '<span> <i class="ace-icon fa fa-angle-double-left bigger-140"></i> </span>',
                    prev: '<span> <i class="ace-icon fa fa-angle-left bigger-150"></i></i></span>',
                    next: '<span>  <i class="ace-icon fa fa-angle-right bigger-150"></i></i></span>',
                    last: '<span> <i class="ace-icon fa fa-angle-double-right bigger-140"></i></span>',
                    onPageClick: function (event, page) {
                        GetMyTasks(page);
                      }
                });
            }

        }

**Comment by jocemarvarela** [comment]
Olá a todos! Se alguém ainda não conseguiu resolver, é só alterar uma linha no arquivo **jquery.twbsPagination.min.js**

Procure esta variável:  **initiateStartPageClick:!0** e altere para **initiateStartPageClick:null**

Para mim funcionou certinho.

**Comment by xavierluz** [comment]
**In my case the code below worked, no problems**
 
var $pagination = $('#pagination'),
                    totalRecords = 0,
                    records = [],
                    displayRecords = [],
                    recPerPage = 10,
                    page = 1,
                    totalPages = 0;
                $.ajax({
                    url: "api/Estoque/Gets",
                    async: true,
                    dataType: 'json',
                    data: { startRec:0, search:'', pageSize:0},
                    success: function (data) {
                        records = data;
                        console.log(records);
                        totalRecords = 10
                        totalPages = 10
                        apply_pagination();
                    }
                });
                function apply_pagination() {
                    $pagination.twbsPagination({
                        totalPages: totalPages,
                        visiblePages: 6,
                        first: 'Pimeiro',
                        prev: 'Anterior',
                        next: 'Próximo',
                        last: 'Último',
                        loop: false,
                        onPageClick: null,
                        onPageClick: function (event, page) {
                            
                            $.ajax({
                                url: "api/Estoque/Gets",
                                async: true,
                                dataType: 'json',
                                data: { startRec: page, search: '', pageSize: 10 },
                                success: function (data) {
                                    records = data;
                                    console.log(records);
                                    totalRecords = data[0].totalRegistros;
                                    totalPages = totalRecords;
                                    apply_pagination();
                                    gernerateCards();
                                }
                            });
                        }
                    });
                }

                gernerateCards = function () {
                    let builder = [];
                    for (var i = 0; i < records.length; i++) {
                        builder.push('<div class="col-sm-6">');
                        builder.push('<div class="row">');
                        builder.push('<div class="col-sm-12">');
                        builder.push('<div class="card">');
                        builder.push('<div class="row">');
                        builder.push('<div class="col-sm-6">');
                        builder.push('<div class="card-body text-center">');
                        builder.push('<h5 class="card-title">Champoo</h5>');
                        builder.push('<p class="card-text">Resumo, prestar bem atenção nos dados, para maiores informações clique no botão <span class="text-info font-weight-bold"> detalhes</span> </p>');
                        builder.push('<span>');
                        builder.push('<a href="#" class="btn btn-outline-info">Detalhes</a>');
                        builder.push('</span>');
                        builder.push('</div>');
                        builder.push('</div>');
                        builder.push('<div class="col-sm-6">');
                        builder.push('<div class="card-header card-header-info">');
                        builder.push('<div class="ct-chart chart-item-material"><span class="text-dark"><i class="fa fa-long-arrow-up"></i> 55% </span> diferença do mês anterior.</div>');
                        builder.push('</div>');
                        builder.push('<br />');
                        builder.push('<p class="card-text">Quantidade  estoque: <span class="text-info font-weight-bold">1589</span></p>');
                        builder.push('</div>');
                        builder.push('</div>');
                        builder.push('</div>');
                        builder.push('</div>');
                        builder.push('</div>');
                        builder.push('</div>');
                    }

                    $('.card-estoque').empty();
                    $('.card-estoque').append(builder.join(""));
                    builder = [];
                }
